"""initial schema

Revision ID: 3cda93e7c477
Revises: 
Create Date: 2026-05-23 12:12:21.933074
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.mixins  # noqa: F401  needed for GUID type referenced below

# revision identifiers, used by Alembic.
revision: str = '3cda93e7c477'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quran_surahs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surah_order', sa.Integer(), nullable=False),
    sa.Column('surah_name_ar', sa.String(length=80), nullable=False),
    sa.Column('surah_name_en', sa.String(length=80), nullable=False),
    sa.Column('ayah_count', sa.Integer(), nullable=False),
    sa.Column('juz_no', sa.Integer(), nullable=False, comment='Starting juz'),
    sa.Column('hizb_no', sa.Integer(), nullable=False, comment='Starting hizb'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quran_surahs'))
    )
    op.create_index(op.f('ix_quran_surahs_surah_order'), 'quran_surahs', ['surah_order'], unique=True)
    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schools'))
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('school_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_users_school_id_schools'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('classes',
    sa.Column('school_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('academic_year', sa.String(length=16), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_classes_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_classes_teacher_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classes'))
    )
    op.create_index(op.f('ix_classes_school_id'), 'classes', ['school_id'], unique=False)
    op.create_index(op.f('ix_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.create_table('students',
    sa.Column('school_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('class_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='student_gender'), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('guardian_name', sa.String(length=200), nullable=True),
    sa.Column('guardian_phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', 'GRADUATED', name='student_status'), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_students_class_id_classes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_students_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_index(op.f('ix_students_class_id'), 'students', ['class_id'], unique=False)
    op.create_index(op.f('ix_students_full_name'), 'students', ['full_name'], unique=False)
    op.create_index(op.f('ix_students_school_id'), 'students', ['school_id'], unique=False)
    op.create_table('memorization_progress',
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'REVIEW_REQUIRED', 'WEAK', 'STRONG', 'MASTERED', name='memorization_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('completion_percent >= 0 AND completion_percent <= 100', name=op.f('ck_memorization_progress_completion_percent_range')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name=op.f('ck_memorization_progress_score_range')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_memorization_progress_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['surah_id'], ['quran_surahs.id'], name=op.f('fk_memorization_progress_surah_id_quran_surahs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_memorization_progress_teacher_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memorization_progress')),
    sa.UniqueConstraint('student_id', 'surah_id', name='uq_memorization_progress_student_surah')
    )
    op.create_index(op.f('ix_memorization_progress_student_id'), 'memorization_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_memorization_progress_surah_id'), 'memorization_progress', ['surah_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memorization_progress_surah_id'), table_name='memorization_progress')
    op.drop_index(op.f('ix_memorization_progress_student_id'), table_name='memorization_progress')
    op.drop_table('memorization_progress')
    op.drop_index(op.f('ix_students_school_id'), table_name='students')
    op.drop_index(op.f('ix_students_full_name'), table_name='students')
    op.drop_index(op.f('ix_students_class_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_classes_teacher_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_school_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('schools')
    op.drop_index(op.f('ix_quran_surahs_surah_order'), table_name='quran_surahs')
    op.drop_table('quran_surahs')
    # ### end Alembic commands ###
