"""add evaluations and observations

Revision ID: 452acfa3204e
Revises: 3cda93e7c477
Create Date: 2026-05-23 12:28:08.156158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.mixins  # noqa: F401  needed for GUID type referenced below

# revision identifiers, used by Alembic.
revision: str = '452acfa3204e'
down_revision: Union[str, None] = '3cda93e7c477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('type', sa.Enum('ORAL_RECITATION', 'REVISION_EXAM', 'MONTHLY_REVIEW', 'ACCURACY_TEST', 'OTHER', name='evaluation_type'), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('tajweed_score', sa.Integer(), nullable=True),
    sa.Column('accuracy_score', sa.Integer(), nullable=True),
    sa.Column('fluency_score', sa.Integer(), nullable=True),
    sa.Column('retention_score', sa.Integer(), nullable=True),
    sa.Column('speed_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('accuracy_score IS NULL OR (accuracy_score >= 0 AND accuracy_score <= 100)', name=op.f('ck_evaluations_accuracy_score_range')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)', name=op.f('ck_evaluations_confidence_score_range')),
    sa.CheckConstraint('fluency_score IS NULL OR (fluency_score >= 0 AND fluency_score <= 100)', name=op.f('ck_evaluations_fluency_score_range')),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name=op.f('ck_evaluations_overall_score_range')),
    sa.CheckConstraint('retention_score IS NULL OR (retention_score >= 0 AND retention_score <= 100)', name=op.f('ck_evaluations_retention_score_range')),
    sa.CheckConstraint('speed_score IS NULL OR (speed_score >= 0 AND speed_score <= 100)', name=op.f('ck_evaluations_speed_score_range')),
    sa.CheckConstraint('tajweed_score IS NULL OR (tajweed_score >= 0 AND tajweed_score <= 100)', name=op.f('ck_evaluations_tajweed_score_range')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_evaluations_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_evaluations_teacher_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index(op.f('ix_evaluations_student_id'), 'evaluations', ['student_id'], unique=False)
    op.create_table('observations',
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('type', sa.Enum('DAILY_NOTE', 'WEAK_PRONUNCIATION', 'MISSING_REVISION', 'IMPROVEMENT', 'PARENT_DISCUSSION', 'GENERAL', name='observation_type'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_observations_student_id_students'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_observations_teacher_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index(op.f('ix_observations_student_id'), 'observations', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_student_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_evaluations_student_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
