"""add notifications table

Revision ID: ccbd632cc0a5
Revises: e7208c7f2769
Create Date: 2026-05-23 13:41:10.090028
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.mixins  # noqa: F401  needed for GUID type referenced below

# revision identifiers, used by Alembic.
revision: str = 'ccbd632cc0a5'
down_revision: Union[str, None] = 'e7208c7f2769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('recipient_user_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('school_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('type', sa.Enum('PROGRESS_REGRESSED', 'LOW_EVALUATION', 'STUDENT_ADDED', 'OVERDUE_REVIEW', 'MANUAL', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_notifications_school_id_schools'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_school_id'), 'notifications', ['school_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_school_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
