"""add audit logs and progress history

Revision ID: e7208c7f2769
Revises: 452acfa3204e
Create Date: 2026-05-23 12:52:10.926806
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.mixins  # noqa: F401  needed for GUID type referenced below

# revision identifiers, used by Alembic.
revision: str = 'e7208c7f2769'
down_revision: Union[str, None] = '452acfa3204e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('school_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'ARCHIVE', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.Enum('STUDENT', 'PROGRESS', 'EVALUATION', 'OBSERVATION', 'CLASS', 'USER', name='audit_entity_type'), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_audit_logs_school_id_schools'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_school_id'), 'audit_logs', ['school_id'], unique=False)
    op.create_table('progress_history',
    sa.Column('progress_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('student_id', app.models.mixins.GUID(), nullable=False),
    sa.Column('surah_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', app.models.mixins.GUID(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'REVIEW_REQUIRED', 'WEAK', 'STRONG', 'MASTERED', name='memorization_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'ARCHIVE', name='audit_action'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.models.mixins.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['progress_id'], ['memorization_progress.id'], name=op.f('fk_progress_history_progress_id_memorization_progress'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_progress_history_teacher_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_history'))
    )
    op.create_index(op.f('ix_progress_history_progress_id'), 'progress_history', ['progress_id'], unique=False)
    op.create_index(op.f('ix_progress_history_student_id'), 'progress_history', ['student_id'], unique=False)
    op.create_index(op.f('ix_progress_history_surah_id'), 'progress_history', ['surah_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_history_surah_id'), table_name='progress_history')
    op.drop_index(op.f('ix_progress_history_student_id'), table_name='progress_history')
    op.drop_index(op.f('ix_progress_history_progress_id'), table_name='progress_history')
    op.drop_table('progress_history')
    op.drop_index(op.f('ix_audit_logs_school_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
